{% set name = "napari-time-series-plotter" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-time_series_plotter-{{ version }}.tar.gz
  sha256: 64b4ee2558a63f98ea491de3e09cedf3a58a235b1099724dfa17687e23bcecc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - napari-matplotlib >=0.2.1
    - napari-plugin-engine >=0.2.0
    - numpy >=1.21.4
    - qtpy >=1.11.2

test:
  imports:
    - napari_time_series_plotter
  commands:
    - pip list
    # - pip check
    - pytest --pyargs napari_time_series_plotter
  requires:
    - pip
    - napari
    - pytest
    - pytest-qt

about:
  home: https://github.com/ch-n/napari-time_series_plotter
  summary: A Plugin for napari to visualize pixel values over the first dimension (time -> t+3D, t+2D) as graphs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ch-n
    - goanpeca
    - jaimergp
