{% set name = "napari-time-series-plotter" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-time_series_plotter-{{ version }}.tar.gz
  sha256: 49b5727bb2362a4c01316c90d7039e76f1337e13170c2e25b8ed171afac09181

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - napari-matplotlib <1.0
    - napari-plugin-engine >=0.2.0
    - numpy >=1.21.4
    - pandas
    - python >=3.8
    - qtpy >=1.11.2

test:
  imports:
    - napari_time_series_plotter
  commands:
    - pip list
    - pip check
  requires:
    - napari
    - pip
    - pyqt

about:
  home: https://github.com/ch-n/napari-time_series_plotter
  summary: A Plugin for napari to visualize pixel values over the first dimension (time -> t+3D, t+2D) as graphs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Chris-N-K
    - goanpeca
    - jaimergp
